CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NAME varchar(60) NOT NULL,
    CPF varchar(20) NOT NULL,
    AGE bigint(3) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID_CUSTOMER_UNIQUE (`ID`)
);

CREATE TABLE IF NOT EXISTS PET
(
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NAME varchar(60) NOT NULL,
    AGE bigint(3) NULL,
    ID_CUSTOMER bigint(20) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID_PET_UNIQUE (`ID`)
);


insert into CUSTOMER(ID, NAME, CPF, AGE) VALUES (9991, 'MANOEL ROSARIO', '07313784236', 20);
insert into CUSTOMER(ID, NAME, CPF, AGE) VALUES (9992, 'GUSTAVO MATOS', '17564233427', 30);
insert into CUSTOMER(ID, NAME, CPF, AGE) VALUES (9993, 'MARIA JOSE', '18767113966', 60);

insert into PET(ID, NAME, AGE, ID_CUSTOMER) VALUES (8881, 'GATO', 5, 9991);
insert into PET(ID, NAME, AGE, ID_CUSTOMER) VALUES (8882, 'CACHORRO', 8, 9991);
insert into PET(ID, NAME, AGE, ID_CUSTOMER) VALUES (8883, 'COBRA', 2, 9992);