CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(60) NOT NULL,
    CPF VARCHAR2(20) NOT NULL,
    AGE NUMBER(3) NULL
);

CREATE TABLE IF NOT EXISTS PET
(
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(60) NOT NULL,
    AGE NUMBER(3) NULL,
    ID_CUSTOMER NUMBER(10,1) NOT NULL
);